name: Test HTML Project

on: push

jobs:
  test-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check index.html exists
        run: test -f index.html

      - name: Print success message
        run: echo "index.html exists!"